version: '2'
networks:
  web:
    external: true
  internal:
    external: false
services:
    db:
      image: mariadb:10.3
      environment:
        MARIADB_ROOT_PASSWORD: $YOU_PASSWORD
      restart: on-failure
      volumes:
       - ./storage:/var/lib/mysql/:Z
      ports:
          - "3306:3306"
      networks:
          - web
