-- CREATE SYSDBA USER WITH ACCESS FROM ANY IP
CREATE USER 'sysdba'@'%' IDENTIFIED BY 'YOUR_PASSWORD';
-- GRANT PERMISSIONS TO SYSDBA USER
GRANT ALL PRIVILEGES ON *.* TO 'sysdba'@'%' WITH GRANT OPTION;
-- RELOAD PRIVILEGES 
-- FLUSH PRIVILEGES;
-- VERIFY IF THIS USER IS CREATED WITH SUCCESS 
SELECT User,Grant_priv,Super_priv FROM mysql.user WHERE User LIKE "sys%";
-- LIST ALL USER IN DATABASE INSTANCE
SELECT User,Grant_priv,Super_priv FROM mysql.user;